apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
  namespace: aula
spec:
  containers:
  - name: mysql
    image: mysql:8.0    
    ports:
      - containerPort: 3306
    env:
        - name: "MYSQL_ROOT_PASSWORD"
          value: root
        - name: "MYSQL_DATABASE"
          value: teste
        - name: "MYSQL_PASSWORD"
          value: "123456789"